
export const PUT_TICKET_INIT_DATA = 'PUT_TICKET_INIT_DATA'

export const GET_TICKET = 'GET_TICKET_REQUEST'
export const GET_TICKET_DONE = 'GET_TICKET_DONE'
export const GET_TICKET_ERROR = 'GET_TICKET_ERROR'

export const CALL_BLOCKPASS_DONE = 'CALL_BLOCKPASS_DONE'